title: ZeroDumb Ethics Journal
author: Zero
email: zero@zerodumb.dev
description: "Ethical hacking reflections, recon lab notes, and the hacker's compass."
baseurl: ""
url: "https://zerodumb.dev"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  style: compressed

# Link the custom CSS
include:
  - assets/css

# Force Jekyll to use the stylesheet