title: ZeroDumb Ethics Journal
author: Zero
email: zero@zerodumb.dev
description: "Ethical hacking reflections, recon lab notes, and the hacker's compass."
baseurl: ""
url: "https://zerodumb.dev"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  style: compressed

# Include custom CSS
include:
  - assets/css/style.css

# SEO settings
lang: en
locale: en_US
twitter:
  username: zerodumb
  card: summary_large_image
  image: /assets/images/og-image.jpg

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "post"
      comments: true
      share: true

# Force Jekyll to use the stylesheet